/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pra;
import java.awt.*;
import javax.swing.*;
import static java.lang.Thread.sleep;

/**
 *
 * @author Zeeshan Liaqaty
 */
public class splashscreen extends javax.swing.JFrame {

    /**
     * Creates new form splashscreen
     */
    public splashscreen() {
        initComponents();
        this.setVisible(true);
    
        
        
    }
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loadpercentage = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        loader = new javax.swing.JLabel();
        per = new javax.swing.JLabel();
        bgimage = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pra/simplebackground-1527070653876-9081.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadpercentage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loadpercentage.setForeground(new java.awt.Color(255, 255, 255));
        loadpercentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(loadpercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 230, -1));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 490, 70));
        jPanel1.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 480, 30));
        jPanel1.add(loader, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 80));

        per.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        per.setForeground(new java.awt.Color(204, 204, 204));
        per.setText("%");
        jPanel1.add(per, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 40));

        bgimage.setBackground(new java.awt.Color(255, 102, 102));
        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pra/Rotate-Loading-Animation.gif"))); // NOI18N
        bgimage.setText("jLabel2");
        bgimage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -10, 850, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(715, 376));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loader;
    private javax.swing.JLabel loadpercentage;
    public javax.swing.JLabel per;
    public javax.swing.JProgressBar progress;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
